#!/bin/bash

# a script for dumping to text files all slow channels in a given time range

set -o errexit
set -o nounset
set -o noclobber

# exit if no arguments
if [ "$#" == "0" ]; then
    cat <<USAGE
Save all slow channel timeseries to text files using geco_dump_channel.
Just a shortcut for calling:

    geco_dump -s start_time -e end_time -l slow

Usage: geco_dump_slow_channels start_time end_time

where

    start_time         is in the form Sep 01 00:00:00 GMT 2015
    end_time           is in the same form as start_time

USAGE
    exit 1
fi


start_time="$1"
end_time="$2"
geco_dump -s "${start_time}" -e "${end_time}" -l slow
