#!/usr/bin/env python
# (c) Stefan Countryman 2016

import os
import subprocess
import math
import sys
import argparse

args = sys.argv
if len(args) == 1 or args[1] == '-h':
    print('This program takes two arguments:\n'
          '1)  the current correction to the frequency as read from the\n'
          '    Monitor2 software on the IBM Thinkpad in the mainstorage room\n'
          '    (which is assumed to be in units of 1e-15, exactly as it\n'
          '    appears in Monitor3), and \n'
          '2)  the drift coefficient.')
    exit()
elif len(args) != 3:
    print('This program takes exactly two arguments')

def calculate_new_delta_f(current_delta_f, drift_coefficient):
    current_delta_f = current_delta_f * 10**-15
    tmp = -1*drift_coefficient/(1+drift_coefficient)
    tmp += current_delta_f
    tmp = tmp * 10**15
    new_delta_f = tmp
    print('The new value to enter into the Monitor2 software is '+ str(new_delta_f))

calculate_new_delta_f(float(args[1]), float(args[2]))
    
