#!/bin/bash
# (c) Stefan Countryman, 2017
# Make a plots for jobspec and put them in public_html for browser viewing on
# ldas-pcdev2.ligo.caltech.edu

olddir=old-plots-`date +%s`
mkdir -p ~/public_html/slow-channels/${olddir}
DATE=`date`

# set default command-line arg values if no channels are specified
if [ "$#" -eq 0 ]; then
    set -- ~/slow-channel-scratch/o1_slow_channels
fi

for jobdir in "$@"; do
    echo "on jobdir ${jobdir}"
    # get git revision and date
    pushd ~/dev/geco_data
    GIT_REV=`git rev-parse HEAD`
    popd

    # get the run title
    pushd ${jobdir}
    # the ugly wrapping python code below just dedents the text so that it is
    # valid python
    RUN="$(python -c 'import textwrap; exec(textwrap.dedent(r"""
        import json
        f = open("jobspec.json")
        run = json.load(f)["slow_channel_plots"]["run"]
        f.close()
        print(run)
    """+" "*4))')"

    # generate plots for each job
    geco_slow_channel_plot.py
    popd

    # move plots around
    pushd ~/public_html/slow-channels
    if [ -d ${RUN} ]; then
        mv ${RUN} ${olddir}
    fi
    mkdir ${RUN}
    pushd ${RUN}
    cp ${jobdir}/*ANALYSIS*png .

    # generate summary page
    cat >index.html <<__HEAD__
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${RUN} Slow Channel Plots </title>
    </head>
    <body>
      <h1>${RUN} Slow Channel Plots</h1>
      <p>Date: ${DATE}</p>
      <p>Git Revision: ${GIT_REV}</p>
__HEAD__
    for imgfile in *png; do
        echo "
          <p>${imgfile}</p>
          <a href=\"${imgfile}\"><img src=\"${imgfile}\"></a>
        " >>index.html
    done
    cat >>index.html <<__TAIL__
    </body>
    </html>
__TAIL__
    popd
    popd
done
