#!/usr/bin/env python
# (c) Stefan Countryman, 2017
# Write a timing witness paper template

import sys, os, glob, gwpy.time, shutil

SCRIPTDIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATEDIRNAME = 'timing_checks.d'
TEMPLATEPATH = os.path.join(SCRIPTDIR, TEMPLATEDIRNAME, 'main.tex')
OUTFILE = os.path.join(outdir, "main.tex")
AUXDIR = os.path.join(SCRIPTDIR, TEMPLATEDIRNAME, 'auxiliary_files')
USAGE = """USAGE:

  $0 GRACEID GPSTIME OUTDIR

  Outputs a timing witness TEX file into the specified output
  directory. The output directory must have the required plots,
  which are generated by the timing_checks.py script. The timing
  witness paper is generated for the given GPS time and GraceID.
"""

if (len(sys.argv) == 0) or ("-h" in sys.argv):
    print(USAGE)
    exit(1)
else:
    graceid = sys.argv[0]
    gpstime = sys.argv[1]
    outdir  = os.path.abspath(sys.argv[2])
    utctime = gwpy.time.tconvert(gpstime).strftime("%c UTC")

# define some straightforward text substitutions for the template TEX file
SUBSTITUTIONS = {
    "$GRACEID": graceid,
    "$GPSTIME": str(gpstime),
    "$UTCTIME": utctime
}

# these are the file name globs for the plots made for each event. these name
# substitutions depend on the files in the directory. this is my lazy solution
# that avoids having to figure out the actual filenames since the plotting
# libraries I wrote are a mess and don't have easily callable functions for
# these.
GLOB_SUBSTITUTIONS = {
    "$LHO_X_DT": "H1..CAL-PCALX_FPGA_DTONE_IN1_DQ-Overlay-*.png",
    "$LHO_Y_DT": "H1..CAL-PCALY_FPGA_DTONE_IN1_DQ-Overlay-*.png",
    "$LLO_Y_DT": "L1..CAL-PCALY_FPGA_DTONE_IN1_DQ-Overlay-*.png",
    "$LLO_X_DT": "L1..CAL-PCALX_FPGA_DTONE_IN1_DQ-Overlay-*.png",
    "$HX_DT_FULL": "H1..CAL-PCALX_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-full-*.png",
    "$HY_DT_FULL": "H1..CAL-PCALY_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-full-*.png",
    "$LY_DT_FULL": "L1..CAL-PCALY_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-full-*.png",
    "$LX_DT_FULL": "L1..CAL-PCALX_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-full-*.png",
    "$HX_DT_ZOOM": "H1..CAL-PCALX_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-zero-crossing-zoom-*.png",
    "$HY_DT_ZOOM": "H1..CAL-PCALY_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-zero-crossing-zoom-*.png",
    "$LY_DT_ZOOM": "L1..CAL-PCALY_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-zero-crossing-zoom-*.png",
    "$LX_DT_ZOOM": "L1..CAL-PCALX_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-zero-crossing-zoom-*.png",
    "$HX_DT_SUPER_ZOOM": "H1..CAL-PCALX_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-super-zoom-*.png",
    "$HY_DT_SUPER_ZOOM": "H1..CAL-PCALY_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-super-zoom-*.png",
    "$LY_DT_SUPER_ZOOM": "L1..CAL-PCALY_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-super-zoom-*.png",
    "$LX_DT_SUPER_ZOOM": "L1..CAL-PCALX_FPGA_DTONE_IN1_DQ-DuoTone-Statistics-super-zoom-*.png",
    "$HX_IRIGB_FULL": "H1..CAL-PCALX_IRIGB_OUT_DQ-Overlay-*.png",
    "$HY_IRIGB_FULL": "H1..CAL-PCALY_IRIGB_OUT_DQ-Overlay-*.png",
    "$LY_IRIGB_FULL": "L1..CAL-PCALY_IRIGB_OUT_DQ-Overlay-*.png",
    "$LX_IRIGB_FULL": "L1..CAL-PCALX_IRIGB_OUT_DQ-Overlay-*.png"
}

# copy auxiliary files to the output directory
for filename in os.listdir(AUXDIR):
    filepath = os.path.join(AUXDIR, filename)
    if not os.path.isfile(filepath):
        shutil.copy(filepath, outdir)

# put ourselves in the output directory
os.chdir(outdir)

# read paper template and substitute out placeholder variables in memory
with open(TEMPLATEPATH) as infile:
    paper = infile.read()
for string in SUBSTITUTIONS.keys():
    paper.replace(string, SUBSTITUTIONS[string])
for string in GLOB_SUBSTITUTIONS.keys():
    # this will fail if a needed file is missing
    path = glob.glob(GLOB_SUBSTITUTIONS[string])[0]
    paper.replace(string, path)

# write the paper template to the output directory
with open(OUTFILE, 'w') as outfile:
    outfile.write(paper)

# compile the PDF
command = ['pdflatex', OUTFILE]
proc = subprocess.Popen(command)
res, err = proc.communicate()
if proc.returncode != 0:
    raise Exception('Something went wrong while generating the PDF file.')
