#!/bin/bash
# (c) Stefan Countryman (2018)
# Watch progress of gstlal download jobs

cry(){ echo "$@" >&2; }

die(){ cry "$@" && usage && exit 1; }

usage(){
    cry "USAGE: $0 [-p] [-f] [-s] [-n REFRESH] [-h]"
    cry
    cry "Watch progress of GSTLAL downloads every 30 seconds. This will fail"
    cry "if you have spaces in any of the script or output directory path"
    cry "names. Sorry."
    cry
    cry "-h shows this help message."
    cry "-p shows job progress"
    cry "-f shows file info/disk usage"
    cry "-s shows slurm queue for current user"
    cry "-n override default of 30 second time delay between refreshes"
}

add_cmd(){ cmd+="$1; "; }

all_scripts(){
    local scripts=(~/dev/geco_data/slurm-jobs/gstlal-subthreshold-raw-*)
    local scripts_fmt="for d in $(printf " '%s'" "${scripts[@]}"); do %s; done"
    add_cmd "${scripts_fmt/%s/$1}"
}

all_outdirs(){
    local outdirs=(/rigel/geco/users/shared/frames/gstlal_offline_subthreshold/gstlal-subthreshold-raw-*)
    local outdirs_fmt="for d in $(printf " '%s'" "${outdirs[@]}"); do %s; done"
    add_cmd "${outdirs_fmt/%s/$1}"
}

time=30
while getopts "hpfsn:" opt; do
    case ${opt} in
        p)  all_scripts '$script -p';;
        f)  all_outdirs 'echo "DIR: $outdir"; ls -lath $outdir | head; echo;';;
        s)  cmd+="squeue -u $(whoami); ";;
        n)  time="${OPTARG}";;
        \?) die "Invalid option: -${OPTARG}";;
    esac
done
[[ -v cmd ]] || usage && exit;

echo watch -n "$time" "${cmd}";
